version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  prometheus:
      image: prom/prometheus:latest
      volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
          - prometheus:/prometheus
      command:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--storage.tsdb.path=/prometheus'
          - '--web.console.libraries=/etc/prometheus/console_libraries'
          - '--web.console.templates=/etc/prometheus/consoles'
          - '--web.enable-lifecycle'
#      network_mode: host
      ports:
          - "9090:9090"


  grafana:
      image: grafana/grafana-oss
      volumes:
          - grafana:/var/lib/grafana
      environment:
          - GF_SECURITY_ADMIN_USER=admin
          - GF_SECURITY_ADMIN_PASSWORD=admin
#          - GF_USERS_ALLOW_SIGN_UP=false
#      network_mode: host
      ports:
          - "3000:3000"


volumes:
  rabbitmq_data:
  prometheus:
  grafana:

networks:
    host:

