global:
    scrape_interval: 15s
    external_labels:
        monitor: 'codelab-monitor'

scrape_configs:
    - job_name: 'bot'
      scrape_interval: 5s
      static_configs:
          - targets: ['host.docker.internal:8083']  # Указывает адрес и порт приложения bot

    - job_name: 'scrapper'
      scrape_interval: 5s
      static_configs:
          - targets: ['host.docker.internal:8084']  # Указывает адрес и порт приложения scrapper

